name: QuestionOfLaw
favicon: null
layout_spectrum: 0.2833706368692219
typography_spectrum: 0.7776363475713879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9834544220939279
  lightness: 0.9670810976531357
  saturation: 0.055568535113707185
  rhythmicContrast: 0.1884851895738393
purpose: []
