name: QuestionOfLaw
favicon: null
layout_spectrum: 0.65455
typography_spectrum: 0.74039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#636566'
    - '#be2225'
    - '#160d09'
    - '#d26668'
  brandStrength: 0.875
  lightness: 0.9670810976531357
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
